### ISSUE TITLE
docker-sdp support configs/secrets as list of strings

### ISSUE THREAD

**Issue by s4ke** [neuroforgede/docker-stack-deploy#1]
This does not work as it crashes the current code that expects a dictionary:

```
secrets:
   my_secret:
      file: /some/path

services:
   my_service:
      secrets:
         - my_secret
```

Instead one has to write

```
secrets:
   my_secret:
      file: /some/path

services:
   my_service:
      secrets:
         - source: my_secret
            target: my_secret
```

which will not work with the secret approach we currently take.

While we could rewrite the list to a dictionary, this feels like a bit much rewriting so we should instead throw a proper error that lets the user know that they should rewrite their yaml slightly.
